use_frameworks!

platform :ios, '9.0'

if Gem::Version.new(`pod --version`) >= Gem::Version.new('1.9.0')
  install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true
else
    raise 'cocoapods 最低要求1.9.0'
    return
end

target 'Example' do
  pod 'MCFrontendKit', :path => '../..'

  target 'MCFrontendKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

post_install do |installer|
  require_relative '../Classes/ProjectConfigurator.rb'
  ProjectConfigurator::configure_project(installer, 'com.binaryparadise.neverland', 'https://y.neverland.life')
end
