# Uncomment the next line to define a global platform for your project
platform :osx, '10.11'

target 'macOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'MCFrontendKit', :path => '../..'

  # Pods for Example

end

post_install do |installer|
  require_relative '../Classes/ProjectConfigurator.rb'
  ProjectConfigurator::configure_project(installer, 'com.binaryparadise.neverland', 'https://y.neverland.life')
end
