use_frameworks!

platform :ios, '9.0'

if Gem::Version.new(`pod --version`) >= Gem::Version.new('1.7.5')
  install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true
else
    raise 'cocoapods 最低要求1.7.5'
    return
end

target 'MCFrontendKit_Example' do
  pod 'MCFrontendKit', :path => '../'

  target 'MCFrontendKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
