platform :ios, '9.0'

install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true

target 'CanaryDemo' do
  
  pod 'Canary', :path => '../..'
  pod 'AFNetworking'
  pod 'CocoaLumberjack/Swift'
  pod 'Masonry'
  pod 'SocketRocket', :modular_headers => true
  
  target 'CanaryDemoTests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end

post_install do |installer|
  require_relative '../CanarySwift/Configuration/ProjectConfigurator.rb'
  ProjectConfigurator::configure_project(installer, '82e439d7968b7c366e24a41d7f53f47d', 'http://127.0.0.1:8081')
end
